Http errors
ThomasG51/bilemo-api pull request #25
Opened 2021-05-21 17:22 UTC by ThomasG51

2021-05-21 17:28 UTC, TBoileau requested changes

2021-05-21 17:28 UTC, TBoileau commented on src/Controller/UserController.php
> +        }
Inutile car par défaut tu attends un User donc il ne peut pas être null

2021-05-21 17:28 UTC, TBoileau commented on src/Listener/ExceptionListener.php
> +        $response = new Response();
Créer une JsonResponse

2021-05-22 07:11 UTC, ThomasG51 commented on src/Listener/ExceptionListener.php
> +        $response = new Response();
renvoi d'une JsonResponse

2021-05-22 07:11 UTC, ThomasG51 commented on src/Controller/UserController.php
> +        }
code supprimer

2021-05-22 07:12 UTC, merged