Api doc
ThomasG51/bilemo-api pull request #28
Opened 2021-05-29 13:22 UTC by ThomasG51

2021-06-04 17:26 UTC, TBoileau requested changes

2021-06-04 17:26 UTC, TBoileau commented on src/Controller/ProductController.php
> +     * @OA\Response(response="200", description="OK", @Model(type=Product::class))
Aller dans le détail

2021-06-04 17:26 UTC, TBoileau commented on src/Controller/UserController.php
> +     * @OA\Response(response="200", description="Get the list of users linked to the connected client", @Model(type=User::class, groups={"without_client"}))
Aller dans le détail

2021-06-05 07:10 UTC, ThomasG51 commented on src/Controller/ProductController.php
> +     * @OA\Response(response="200", description="OK", @Model(type=Product::class))
ajout du detail de _links et _embedded

2021-06-05 07:10 UTC, ThomasG51 commented on src/Controller/UserController.php
> +     * @OA\Response(response="200", description="Get the list of users linked to the connected client", @Model(type=User::class, groups={"without_client"}))
ajout du detail de _links et _embedded

2021-06-05 07:12 UTC, merged